version: '3.8'

services:

  app:
    build:
      context: .
      target: development
      args:
        - USER_ID=${UID:-1000}
    command: tail -f /dev/null
    volumes:
      - .:/app
    ports:
      - ${WEB_PORT:-80}:3000

  proxy:
    image: imjacobclark/cors-container
    ports:
      - ${PROXY_PORT:-8000}:3000
