services:

  app:
    build:
      context: .
      target: development
      args:
        USER_ID: ${USER_ID:-1000}
    volumes:
      - .:/usr/src/app
    ports:
      - ${HTTP_PORT:-80}:3000
    hostname: app
    tty: true

  proxy:
    image: caddy:2.6.2-alpine
    volumes:
      - ./deployments/containers/caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - ${PROXY_PORT:-8000}:3000
